export const ledgerStyles = {
  viewViewportContainer: {
    display: "flex",
    flexDirection: "column",
    position: "relative",
    height: "100%",
    top: 0,
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: "#f1f5f9", // Crisp light-grey ERP backdrop
    overflow: "hidden",
    fontFamily: "JetBrains Mono, Fira Code, Monaco, Consolas, monospace",
  },
  staticHeaderBlock: {
    padding: "3px 0px",
    flexShrink: 0,
    width: "100%",
    boxSizing: "border-box",
    // backgroundColor: "#dcdada",
    borderBottom: "1px solid #0f172a",
    paddingBottom: 6,
    marginBottom: 4,
  },
  actionHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    gap: "12px",
    height: "44px",
  },
  pageTitle: {
    fontSize: "13px",
    fontWeight: "700",
    color: "#38bdf8",
    margin: 0,
    textTransform: "uppercase",
    letterSpacing: "0.5px",
  },
  pageSubtitle: {
    fontSize: "11px",
    color: "#94a3b8",
    marginTop: "0px",
    margin: 0,
  },
  filterControlPanel: {
    display: "flex",
    gap: "8px",
    backgroundColor: "#ffffff",
    marginTop: "0px",
    padding: "6px 12px",
    borderRadius: "0px",
    borderBottom: "1px solid #cbd5e1",
    alignItems: "center",
    flexWrap: "nowrap",
  },
  searchContainer: {
    display: "flex",
    alignItems: "center",
    backgroundColor: "#f8fafc",
    borderRadius: "0px",
    border: "1px solid #cbd5e1",
    padding: "0 8px",
    flex: 1,
    height: "28px",
  },
  searchIcon: { color: "#64748b", marginRight: "6px" },
  searchInput: {
    backgroundColor: "transparent",
    border: "none",
    outline: "none",
    width: "100%",
    padding: "4px 0",
    fontSize: "12px",
    color: "#1e293b",
    fontFamily: "inherit",
    fontWeight: "600",
  },
  exportButton: {
    backgroundColor: "#16a34a",
    color: "#ffffff",
    height: "28px",
    padding: "0 12px",
    borderRadius: "0px",
    border: "1px solid #15803d",
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: "11px",
    fontWeight: "700",
    textTransform: "uppercase",
  },
  errorAlertCard: {
    display: "flex",
    alignItems: "center",
    backgroundColor: "#fef2f2",
    borderLeft: "4px solid #dc2626",
    borderTop: "1px solid #fee2e2",
    borderRight: "1px solid #fee2e2",
    borderBottom: "1px solid #fee2e2",
    color: "#991b1b",
    padding: "6px 12px",
    borderRadius: "0px",
    marginTop: "4px",
    fontSize: "11px",
    fontWeight: "600",
  },
  dynamicScrollBodyWrapper: {
    flex: 1,
    padding: "8px 12px 12px 12px",
    overflow: "hidden",
    display: "flex",
    flexDirection: "column",
    boxSizing: "border-box",
  },
  tableCardContainer: {
    backgroundColor: "#ffffff",
    borderRadius: "0px",
    border: "1px solid #cbd5e1",
    display: "flex",
    flexDirection: "column",
    flex: 1,
    overflow: "hidden",
    width: "100%",
    boxSizing: "border-box",
  },
  overflowTableScroller: {
    flex: 1,
    overflowY: "auto",
    overflowX: "auto",
    width: "100%",
    position: "relative",
    backgroundColor: "#ffffff",
  },
  masterTableElement: {
    width: "100%",
    borderCollapse: "collapse",
    textAlign: "left",
    fontSize: "12px",
  },
  stickyTableHeader: {
    position: "sticky",
    top: 0,
    backgroundColor: "#f8fafc",
    zIndex: 10,
  },
  thElement: {
    padding: "8px 10px",
    color: "#475569",
    fontWeight: "700",
    textTransform: "uppercase",
    fontSize: "11px",
    letterSpacing: "0.2px",
    backgroundColor: "#f1f5f9",
    borderBottom: "2px solid #cbd5e1",
    borderRight: "1px solid #cbd5e1", // Visible grid borders like an Excel/Tally ledger matrix
  },
  tableBodyRowElement: {
    borderBottom: "1px solid #e2e8f0",
  },
  selectedTableRow: {
    backgroundColor: "#9fc5f6",
  },
  tdElement: {
    padding: "6px 10px",
    color: "#1e293b",
    whiteSpace: "nowrap",
    fontWeight: "600",
    borderRight: "1px solid #e2e8f0",
    borderBottom: "1px solid #e2e8f0",
  },
  badgeApproved: {
    backgroundColor: "#f0fdf4",
    color: "#166534",
    padding: "0px 4px",
    border: "1px solid #bbf7d0",
    borderRadius: "0px",
    fontSize: "10px",
    fontWeight: "700",
  },
  badgeVoid: {
    backgroundColor: "#fef2f2",
    color: "#991b1b",
    padding: "0px 4px",
    border: "1px solid #fecaca",
    borderRadius: "0px",
    fontSize: "10px",
    fontWeight: "700",
  },
  paginationRow: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    padding: "6px 12px",
    backgroundColor: "#f1f5f9",
    borderTop: "2px solid #cbd5e1",
    flexShrink: 0,
    height: "36px",
  },
  paginationText: {
    fontSize: "11px",
    color: "#475569",
    fontWeight: "700",
  },
  paginationButtonPair: { display: "flex", gap: "4px" },
  pagBtnActive: {
    backgroundColor: "#ffffff",
    border: "1px solid #cbd5e1",
    color: "#1e293b",
    padding: "3px 10px",
    borderRadius: "0px",
    fontWeight: "700",
    fontSize: "11px",
    cursor: "pointer",
  },
  pagBtnDisabled: {
    backgroundColor: "#e2e8f0",
    border: "1px solid #cbd5e1",
    color: "#94a3b8",
    padding: "3px 10px",
    borderRadius: "0px",
    fontSize: "11px",
    cursor: "not-allowed",
  },
  loadingWrapperGrid: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    minHeight: "200px",
    width: "100%",
    backgroundColor: "#ffffff",
    fontSize: "12px",
    fontWeight: "700",
    color: "#64748b",
  },
  emptyStateBlock: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    minHeight: "200px",
    width: "100%",
    backgroundColor: "#ffffff",
    fontSize: "12px",
    fontWeight: "700",
    color: "#94a3b8",
  },
  exportButtonDisabled: {
    backgroundColor: "#cbd5e1",
    border: "1px solid #94a3b8",
    color: "#94a3b8",
    cursor: "not-allowed",
  },
};
